POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmMiLCJpZCI6IjYxOTU4MmMyMjM1ZWRhNDg4ZTZlNGVmMCIsImlhdCI6MTYzNzE4ODI5NCwiZXhwIjoxNjM3MTkxODk0fQ.I05ukB0-skPEger2kOtEM7CK0pnKlKkQ8C9J5rPxP04

{
  "title": "From creative director to programmer in 18 months",
  "author": "Marc Hermann",
  "url": "https://www.tricklabor.com",
  "likes": 56
}